### ISSUE TITLE
A40: Permissive kernel

### ISSUE THREAD

**Issue by ponces** [SamarV-121/android_kernel_samsung_m20lte#1]
Hi,

First of all, thank you for your great work on this kernel!
I was not able to run this kernel as enforcing, it seems that by default it is permissive.
Is this normal? Is this supposed to be like this?
Is there any way to force it to enforcing without resorting to setenforce commands?

[last_kmsg.txt](https://github.com/SamarV-121/android_kernel_samsung_universal7904/files/5542654/last_kmsg.txt)
[logcat.txt](https://github.com/SamarV-121/android_kernel_samsung_universal7904/files/5542655/logcat.txt)
[pmsg-ramoops-0.txt](https://github.com/SamarV-121/android_kernel_samsung_universal7904/files/5542656/pmsg-ramoops-0.txt)

**Comment by SamarV-121** [comment]
welp, I've hardcoded SELinux to permissive on Non-OneUI variant
https://github.com/SamarV-121/android_kernel_samsung_universal7904/commit/d32e21c9d25c2ce0f7cd9d664b073c99e9267ec9

**Comment by ponces** [comment]
Wasn't this commit reverted on [b6d4e2b](https://github.com/SamarV-121/android_kernel_samsung_universal7904/commit/b6d4e2b03b52f81da94420b8ca15a6f3db22aaee)?

**Comment by SamarV-121** [comment]
https://github.com/SamarV-121/android_kernel_samsung_universal7904/blob/fuse/build.sh#L42
https://github.com/SamarV-121/android_kernel_samsung_universal7904/blob/fuse/build.sh#L144

**Comment by ponces** [comment]
Ahhh understood...
Is selinux blocking any kernel functionality?

**Comment by SamarV-121** [comment]
what do you mean ?

**Comment by ponces** [comment]
Btw, thank you for the quick replies!
Why did you need it to force it to permissive?
Just trying to understand, don't get me wrong...

**Comment by SamarV-121** [comment]
some GSIs doesn't boot with enforcing

**Comment by ponces** [comment]
As I'm using phhusson's GSI (enforcing), I don't need a permissive kernel.
I'll build an enforcing version for me 👍 
Thank you for your clarifications and help!
Issue closed!
